banesullivan/scooby

scooby/extras.py
`MKL_INFO` is very interesting. Unfortunately, most people do not have `mkl` installed explicitly. One other way to get the info is from `numexpr`, which is added by this PR. We might add more possibilities when we find out about them.
=> Add numexpr for MKL_INFO

scooby/report.py
I have no idea why I have `text_width=54` in the versions-script (empymod, emg3d, SimPEG). There must have been a reason. I think too keep it compact.
However, now scooby has several large outputs that then break line (`[GCC 7.3.0]` in the example below) or overflow (`-with-debian-buster-sid` in the example below).
This PR sets the default width to 80, which is usually a minimum terminal width; default flake8-width etc.
=> Adjust default text_width

.travis.yml, scooby/__init__.py, scooby/extras.py, scooby/report.py
Resolve #14 
Always puts `scooby` last and allows users to sort packages alphabetically if desired.
=> Report Scooby version

README.md
Just in case we make changes to the API, have projects copying our example use explicit arguments
=> Explicitly pass arguments in Report example

setup.py
Installing fails in CentOS Python3.6
=> Using UTF-8 for reading long description

scooby/report.py, tests/test_scooby.py
This adds an option for users/downstream projects to add extra meta information in the header. For example, check out https://github.com/pyvista/pyvista/pull/512
=> Add extra meta info pairs

.travis.yml, README.md, scooby/__init__.py, scooby/knowledge.py, scooby/report.py, scooby/tracker.py, tests/test_scooby.py
Here is a neat way to easily generate a report at the end of a notebook that has imported many packages without having to list all the packages when creating a report:
- Everything is tracked except libraries you may have only fetched primitive types from (e.g. a float from `scipy.constants`)
```py
import numpy as np
import matplotlib.pyplot as plt
import pyvista as pv
import pandas as pd
from SimPEG import (
Mesh, Maps, Utils, DataMisfit, Regularization,
Optimization, Inversion, InvProblem, Directives
)
import SimPEG.EM as EM
import inspect
import sys
import os
from pymatsolver import PardisoSolver
from scipy.constants import mu_0 # a float value
def foo():
pass
class goo():
pass
import scooby
scooby.Inspection(globals(), sort=True)
```
*`jupyterthemes` is an extra in there because my …
=> Add import patcher to track all imported packages

scooby/__init__.py, scooby/knowledge.py, scooby/report.py, scooby/tracker.py, tests/test_scooby.py
Add a `to_dict()` method to serialize the report. This can be useful to, e.g., attach meta-data to data written to a file.
```
In [1]: import scooby                                                                                 
In [2]: scooby.Report().to_dict()                                                                     
Out[2]: 
{'Date': 'Wed Mar 18 06:36:40 2020 CET',
'OS': 'Linux',
'CPU(s)': 4,
'Machine': 'x86_64',
'Architecture': '64bit',
'RAM': '7.7 GB',
'Environment': 'IPython',
'Python': '3.7.6 (default, Jan  8 2020, 19:59:22) \n[GCC 7.3.0]',
'numpy': '1.18.1',
'scipy': '1.4.1',
'IPython': '7.12.0',
'matplotlib': '3.1.3',
'scooby': '0.5.2',
'MKL': 'Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications'}
```
=> Add to_dict() for serialization

scooby/knowledge.py
It just happened on an installation of mine that import of a package which scooby failed, because of a 
```
AttributeError: module 'mkl' has no attribute 'get_version_string'
```
So it was able to import `mkl`, but `mkl` had no version info. This fix ensures that that won't make scooby fail.
=> Check if `mkl` has attribute `get_version_string`

README.md, scooby/knowledge.py, tests/test_scooby.py
Ran into an issue whereby I couldn't compare a development version.  For example:
```python
assert scooby.meets_version('0.28.0dev0', '0.25.2')
```
This PR no automatically converts any non-numeric value to a `0` for the purpose of comparison.
=> Add non-numeric version checking

scooby/knowledge.py
When using `pyinstaller`, the standard library directory is different than the one `sysconfig` identifies.  This results in the failure to run `scooby.Report`.
=> Fix standard lib when frozen

scooby/report.py
Resolve #59 
```py
>>> scooby.Report(additional=['pydata_sphinx_theme'])
Date: Mon Apr 12 13:52:52 2021 MDT
OS : Darwin
CPU(s) : 16
Machine : x86_64
RAM : 64.0 GiB
Environment : Python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38)
[Clang 11.0.1 ]
pydata_sphinx_theme : 0.6.0
numpy : 1.18.1
scipy : 1.4.1
IPython : 7.14.0
matplotlib : 3.2.1
scooby : 0.5.6
```
=> Use length of longest package name for formatting

scooby/report.py
We recently encountered an issue which was related to the Filesystem in use. This was related to the use of a NFS File System.
I added this approach [https://stackoverflow.com/a/35291824/10504481](url) from the user gena2x to get the file system.
Tested with:
```py
import scooby
scooby.Report()
Date: Sun Apr 18 19:47:45 2021 Mitteleuropäische Sommerzeit
OS : Windows
CPU(s) : 16
Machine : AMD64
RAM : 15.9 GiB
Environment : Python
File system : NTFS
Python 3.9.4 (default, Apr  9 2021, 11:43:21) [MSC v.1916 64 bit (AMD64)]
```
```py
>>> import scooby
>>> scooby.Report()
Date: Sun Apr 18 19:51:57 2021 CEST
OS : …
```
=> Add "File system" as OS/Platform detail

requirements_test.txt, scooby/report.py, tests/test_scooby.py
A potential solution to #73 
This has a bare `except` which is frowned upon. Also the test I added here will only work if you have pyvips improperly installed. We may want a better test or to scrap this test
=> Catch errors on import

scooby/knowledge.py, scooby/report.py
I went ahead and just skipped this for Windows altogether, what do you think, @Huite and @akaszynski?
Resolves #75, resolves https://github.com/pyvista/pyvista/issues/1961
=> Patch for #75: File system seg fault on Windows

.github/workflows/lint.yml, .github/workflows/pythonpackage.yml, .github/workflows/release.yml, scooby/knowledge.py, scooby/report.py
If `psutil` is not installed, it will not know the file system.
Before #76, this was then simply omitted. Since then, it is always shown, but as `'unknown'` if `psutil` is not installed.
This PR undoes that.
I did also the following changes to the actions (if you prefer a separate PR @banesullivan let me know):
- `pythonpackage.yml`: Remove Python 3.6, add Python 3.10
- `lint.yml` & `release.yml`: Move from Python 3.8 to Python 3.9
Resolves #78
=> Better handling of file system for #78

setup.py
Following up on https://github.com/banesullivan/scooby/pull/80#discussion_r817162641
Drops support for Python 3.6
=> Set minimum of Python 3.7

scooby/report.py
Currently, the `Report()` fails if there is an empty package list, which you get if you call
```
import scooby
scooby.Report(optional=[])
```
This PR fixes this, so it works just nicely (it always worked with the `_repr_html`, there was no issue there).
Example output (with the fix):
```
Date: Fri Jul 22 17:08:49 2022 CEST
OS : Linux
CPU(s) : 4
Machine : x86_64
RAM : 7.7 GiB
Environment : IPython
File system : ext4
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)
[GCC 9.4.0]
Intel(R) oneAPI Math Kernel Library Version 2022.0-Product Build 20211112
for Intel(R) 64 architecture applications
------------------------------------------------------------------------------- …
```
=> Fix bug for empty package list

scooby/knowledge.py
Resolves #79 by removing our dependency on `distutils`.
=> use sysconfig for sitepath

scooby/report.py
Fixes the bad html styling for dark themes. The fix is done by simply removing all hard-coded colours, and leaving it up to the theme to decide on colours.
I tried a few of the Jupyter themes available:
I hope this would be OK with you @akaszynski (pinging you as you started with #82).
Closes #62
=> Fix html styling

scooby/report.py
My proposition as an alternative to #82  @akaszynski - what do you think?
It does the following:
- If `ncol=1`, it left-aligns everything.
- It adds a new `max-width` parameter, with which the user can control the max-width of the table.
- I tried to include all the other little cleaning-up bits you put into #82.
An example how this "compact" layout looks:
=> Introduce a compact layout for ncol=1

scooby/knowledge.py, scooby/report.py, scooby/tracker.py, tests/test_scooby.py
Helps #79 to speed up scooby import time since `distutils` is imported for a lesser used method `get_standard_lib_modules()`
We can remove/deprecate in a follow-up PR. This change speeds up the import time from 0.378s to 0.044s for me
cc @prisae
=> Improve load time

setup.py
This follows the [trunk based development](https://trunkbaseddevelopment.com/) release pattern used for PyVista by:
- Setting the `main` branch to MAJOR.<MINOR + 1>.dev0
- Follow semantic versioning by creating release branches so we can do patch releases for bug fixes without having to make a new minor release.
- Getting us ready to bump the release branch and tag it.
=> Bump main to 0.7.dev0

scooby/report.py, tests/test_scooby.py
Fixes an issue where our typical methods of uncovering a version fail for some packages by falling back to package-resoources if available to get the distribution version.
There may be justification for making this the default, but for now, I have tagged it on as a final fallback.
One particular package that needs this is `pythreejs`.
Main:
```
$ scooby pythreejs
...
Python 3.9.13 (main, Aug 25 2022, 18:24:45)  [Clang 12.0.0 ]
pythreejs : Version unknown
```
This branch
```
$ scooby pythreejs
...
Python 3.9.13 (main, Aug 25 2022, 18:24:45)  [Clang 12.0.0 ]
pythreejs : 2.4.1
```
=> Add package resources version fallback

.gitignore, requirements_test.txt, tests/test_scooby.py
Create a local dummy package without a version. Because pip/PyPI gives it automatically a version number 0.1.0 if None is provided.
=> Replace no_version from PyPI to local

requirements_test.txt
`bs4` is a dummy package. It's published on PyPI but distributions usually only ship `beautifulsoup4`.
=> Replace bs4 with beautifulsoup4

setup.py
Using `3.7.*` was turned into an error by a recent version of `packaging` and won't allow installing, see
https://github.com/pypa/packaging/commit/068a0b5975a95a5cc30262599ca29bb6ceabe4af
=> setup.py: fix python_requires version specifier

.pre-commit-config.yaml
This should fix:
```
raise RuntimeError("The Poetry configuration is invalid:\n" + message)
RuntimeError: The Poetry configuration is invalid:
- [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```
It does and then ends up with this message:
```
[INFO] Installing environment for https://github.com/pycqa/pydocstyle.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Passed
isort....................................................................Passed …
```
=> .pre-commit-config.yaml: Upgrade isort to 5.12.0

.github/workflows/pythonpackage.yml, requirements_test.txt
This PR addresses issue #110 by removing `codecov` from `requirements_test.txt` and updating the `codecov` `GitHub Action` in `pythonpackage.yml` to `v3` (`v2+` required to use new uploader instead of `bash` uploader).
This should completely fix the issue, but in case additional steps are required to properly setup `codecov`, a repository admin may need to perform additional steps from the [deprecation guide](https://docs.codecov.com/docs/deprecated-uploader-migration-guide).
=> Fix `codecov` to Use New Uploader

.github/workflows/pythonpackage.yml, setup.py
Dropping Python 3.7 support given that it is past end of life and PyVista has dropped it. See also https://github.com/banesullivan/scooby/pull/109#issuecomment-1732663856
cc @Gryfenfer97
=> Drop Python 3.7

.gitignore, scooby/__main__.py, scooby/knowledge.py, scooby/report.py, scooby/tracker.py, setup.py
add type hints
I am still not sure about the type of `extra_meta` in `Report` because there is check about it being a list.
Should fix #108
=> add type hints

README.md, scooby/knowledge.py, scooby/report.py, tests/test_scooby.py
Follow up to #101 to make `importlib.metadata`'s `version` the default mechanism for retrieving package versions now that scooby is Python 3.8+ and this module is no longer provisional as of Python 3.10
Also cleans up a deprecation warning for a testing tool
=> importlib.metadata.version is now default mechanism

README.md, scooby/__init__.py, scooby/__main__.py, scooby/report.py, tests/test_scooby.py
The CLI that @prisae implemented is awesome! 
I found myself wanting to take it a step further. I wanted scooby to generate insightful reports about packages that do not have a `Report` class implemented directly.
These changes let the CLI fallback to using `pkg_resources` to get the distribution requirements to autogenerate a report about the specified package and its direct dependencies.
For example, `matplotlib`
```bash
$ scooby -r matplotlib
Date: Fri Oct 20 00:27:27 2023 PDT
OS : Darwin
CPU(s) : 8
Machine : arm64
RAM : 16.0 GiB
Environment : Python
File system : apfs
Python 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31)
[Clang 14.0.6 ]
matplotlib : 3.7.1
contourpy : …
```
=> Autogenerate Reports for any package and its dependencies

.flake8, scooby/report.py
It would be nice and helpful if we also have the name and version for the Linux distribution under OS .  It looks like this for my os.
```
Date: Thu Apr 18 18:36:14 2024 CEST
OS : Linux (Gentoo 2.14)
CPU(s) : 32
Machine : x86_64
RAM : 62.6 GiB
Environment : Python
File system : ext4
Python 3.11.8 (main, Mar 21 2024, 00:53:58) [GCC 13.2.1 20240113]
numpy : 1.26.3
scipy : 1.12.0
IPython : 8.21.0
matplotlib : 3.8.2
scooby : 0.9.2
```
The PR adds some placeholder for other platforms (Mac/Windows/Java) and would need some parsing for these platforms. I don't have access to them to test.
Thanks for considering this …
=> ENH. Add name and version of current linux distribution. 

tests/test_scooby.py
This should make no difference at all in your CI, but it makes it easier to run more tests in situations where the Python interpreter might have a different name, e.g. `python3` in some Linux distributions. (I am working on a `python-scooby` package for Fedora.)
https://docs.python.org/3/library/sys.html#sys.executable
=> In tests, use sys.executable instead of assuming "python"

scooby/report.py
Accessing `Report.packages` with the public API is required in order for the package sorting to be triggered. Currently, `Report._packages` is instead accessed, and thus no sorting occurs. This PR fixes this.
EDIT:
Reproducible with
``` python
import pyvista as pv
pv.Report(sort=True)
```
The packages will _not_ be sorted.
=> Fix sorting packages with Report

scooby/report.py, tests/test_scooby.py
Show the timezone in UTC since it makes the reports more consistent and is also a bit more private since it won't implicitly reveal geographic location.
=> Report time in UTC timezone
